// <auto-generated />
using System;
using ISC567Web.DAL;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace ISC567Web.Migrations
{
    [DbContext(typeof(ISC567WebContext))]
    partial class ISC567WebContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.14-servicing-32113")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("ISC567Web.Models.Advertiser", b =>
                {
                    b.Property<int>("AdvertiserID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("CompanyID");

                    b.Property<string>("EmailAddress");

                    b.Property<string>("FirstName");

                    b.Property<string>("LastName");

                    b.Property<string>("PhoneNumber");

                    b.HasKey("AdvertiserID");

                    b.HasIndex("CompanyID");

                    b.ToTable("Advertisers");
                });

            modelBuilder.Entity("ISC567Web.Models.Company", b =>
                {
                    b.Property<int>("CompanyID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CompanyName");

                    b.HasKey("CompanyID");

                    b.ToTable("Companies");
                });

            modelBuilder.Entity("ISC567Web.Models.Event", b =>
                {
                    b.Property<int>("EventID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("AdvertiserID");

                    b.Property<DateTime>("Date");

                    b.Property<string>("Description");

                    b.Property<int?>("EventCategoryID");

                    b.Property<string>("EventLocation");

                    b.Property<string>("EventLogo");

                    b.Property<string>("EventName");

                    b.Property<bool>("Promotional");

                    b.HasKey("EventID");

                    b.HasIndex("AdvertiserID");

                    b.HasIndex("EventCategoryID");

                    b.ToTable("Events");
                });

            modelBuilder.Entity("ISC567Web.Models.EventCategory", b =>
                {
                    b.Property<int>("EventCategoryID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CategoryName");

                    b.Property<string>("EventCategoryLogo");

                    b.HasKey("EventCategoryID");

                    b.ToTable("EventCategories");
                });

            modelBuilder.Entity("ISC567Web.Models.Advertiser", b =>
                {
                    b.HasOne("ISC567Web.Models.Company", "Company")
                        .WithMany("Advertisers")
                        .HasForeignKey("CompanyID");
                });

            modelBuilder.Entity("ISC567Web.Models.Event", b =>
                {
                    b.HasOne("ISC567Web.Models.Advertiser", "Advertiser")
                        .WithMany("Events")
                        .HasForeignKey("AdvertiserID");

                    b.HasOne("ISC567Web.Models.EventCategory", "EventCategory")
                        .WithMany("Events")
                        .HasForeignKey("EventCategoryID");
                });
#pragma warning restore 612, 618
        }
    }
}
